name: API test
run-name: API testing
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.2.2
      - name: Install Java and Maven
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Run API Test
        run: mvn test -f coingecko-api
      - name: Upload API Report
        uses: actions/upload-artifact@v4.6.1
        if: always()
        with:
          name: api-report
          path: coingecko-api/target/surefire-reports
          retention-days: 30
          
          
        
    
