name: API test
run-name: API testing
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '8'
            distribution: 'adopt'
            cache: maven
          
      - name: Run API Test
        run: mvn test -f coingecko-api
          
          
        
    
